### ISSUE TITLE
Using plugins with importmap

### ISSUE THREAD

**Issue by viktorshamal** [rbui-labs/rbui#91]
Hi,

Thanks for making a great framework!

When following the install guide using importmap, you have a warning that says:

```
Tailwind plugins not compatible with importmaps
This means that animation using tailwind-animate plugin will not work. 
I am thinking of a new way to implement this, most likely with a stimulus controller for animations.
```

But if i run `bin/importmap pin tailwind-animate` and add the following to `tailwind.config.js` then it works fine.

```
  plugins: [
    require("../vendor/javascript/tailwindcss-animate"),
  ]
```

I'm just wondering if this is a bad idea, or if you just weren't aware. Then you could save the trouble of rewriting the animations.

**Comment by viktorshamal** [comment]
You're welcome! Rails-importmap changed at some point from pointing at the CDN to actually downloading the file automatically and serving it from Rails. It probably wouldn't have worked before with the CDN method.

**Comment by cirdes** [comment]
@viktorshamal ,

I was able to confirm that it is working when using:

```
  plugins: [
    require("../vendor/javascript/tailwindcss-animate"),
  ]
```

**Comment by SethHorsley** [comment]
fixed with https://github.com/rbui-labs/rbui/pull/162.
try again with main and the installers should work. I'll upload an example repo with the correct importmaps.rb file.
and thanks @viktorshamal for the suggestion
